### ISSUE TITLE
Indentation issues?

### ISSUE THREAD

**Issue by davestewart** [davestewart/alias-hq#10]
Hey @pankajpatel,

I noticed in your [commit](https://github.com/time2hack/t2h-gatsby/commit/9e18cd00fd74587dfad26d78e6bc68fb20a82983) that indentation was updated along with aliases.

Was this something you did yourself, or was it done by Alias HQ?

If Alias did this, I'd see that as a bug, and would like to put it right.

**Comment by pankajpatel** [comment]
It was done by alias-hq, what's the bug you see?

**Comment by pankajpatel** [comment]
Though there was prettier fixing up the files as well, so I don't think it is an issue.

**Comment by davestewart** [comment]
Looks like the indents for all lines were adjusted:

![image](https://user-images.githubusercontent.com/132681/92598927-6ff1de80-f2a1-11ea-843e-eda1e123f759.png)

Sounds like it was just Prettier, so I'll close this.

Thanks!
