### ISSUE TITLE
Error! Unexpected token ] in "tsconfig.json" at position 666

### ISSUE THREAD

**Issue by raphael10-collab** [davestewart/alias-hq#28]
My tsconfig.json is : 

    {
      "compilerOptions": {
        "target": "esnext",
        "module": "commonjs",
        "lib": ["dom", "es2015", "esnext"],
        "outDir": "dist",
        "jsx": "react",
        "baseUrl": "./src",
        "paths": {
          "@src/*": ["src/*"],
          "@sections/*": ["src/app/sections/*"],
          "@app/*": ["src/app/*"]
        },
        "strict": true,
        "sourceMap": true,
        "skipLibCheck": true,
        "noImplicitAny": false,
        "noImplicitThis": false,
        "moduleResolution": "node",
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
        "resolveJsonModule": true,
        "allowJs": true
      },
      "include": ["src/**/*"],
      "exclude": [
        "src/index.js",
        "dist",
      ]
    }

Executing `alias-hq CLI` : 

    ./node_modules/.bin/alias-hq 

      == Alias HQ ==

      Error! Unexpected token ] in "tsconfig.json" at position 666

      Edit the file to fix this, then try again

Why? How to solve the problem?

    typescript : v.4.1.5

**Comment by davestewart** [comment]
```
"exclude": [
    "src/index.js",
    "dist", <-- here
  ]
```

**Comment by IanVS** [comment]
tsconfig files aren't technically treated like pure json files, and typically allow trailing commas and comments.  Perhaps you could consider using https://github.com/dominikg/tsconfck to parse it?

**Comment by davestewart** [comment]
Seems like a fair request! Want to PR?

**Comment by davestewart** [comment]
The other option would be to replace with a regex...

**Comment by IanVS** [comment]
I can take a look at making a PR, sure.  

Seems safer and less buggy to use a parser that's built for the purpose, but if you'd rather do it with a regex that's fine too, but I'm not sure I'm up for writing it.  ;)

**Comment by davestewart** [comment]
Actually, the fact that tsconfck resolves `extends` would also fix #30...

**Comment by IanVS** [comment]
FWIW, tsconfck.parse is an async function, so it's going to mean that the rest of the functions using it will need to become async as well.  So I guess it means it'll probably need a major version bump.

**Comment by IanVS** [comment]
I opened https://github.com/davestewart/alias-hq/pull/36 if you want to take a quick look.  I don't have time to finish it up at the moment, but I'll come back to it when I can.

**Comment by davestewart** [comment]
> FWIW, tsconfck.parse is an async function

Crap... just seen the PR; yup lots of file changes.

Not sure how that's going to work if they bubble up to the CLI level...

**Comment by IanVS** [comment]
I think it shouldn't effect the cli, but I'll check it later.  What is the alias cli?  I can take a look at that too.

**Comment by davestewart** [comment]
> What is the alias cli?

It's a major component of this library:

- https://github.com/davestewart/alias-hq/blob/master/docs/cli/cli.md

> I can take a look at that too.

Sure. But I don't want to rewrite the whole thing and force users to go async, just to solve some trailing commas and merging a few paths...

I've posted the question here:

- https://github.com/dominikg/tsconfck/discussions/18

**Comment by davestewart** [comment]
It seems the asynchronous nature of the lib is simply due to using using the async version of Node's Fs functions: 

https://github.com/dominikg/tsconfck/blob/60f63d821a5aefdaa8f81ab22cc7e00fbc3e973d/src/util.ts#L26

Not sure why the author chose not to use the sync version of Node's filesystem functions which I think would make it more flexible?

**Comment by IanVS** [comment]
Yeah I think you're right, it's probably not worth a breaking change to the api.  

Another option is to use typescript's own `parseConfigFileTextToJson()` function, but I'm not sure if you want to add typescript as a dependency, either.  https://github.com/microsoft/TypeScript/issues/44573#issuecomment-861843319

It's a bummer, because typescript by default adds comments to the tsconfig.json in a new project.

**Comment by davestewart** [comment]
Thanks for taking a look anyway. Food for thought if nothing else!

And yeah, I think best to keep this sync + JS compatible.

I'll reopen so this can be solved anyway.

Thanks for bringing the config issue to my attention!

**Comment by IanVS** [comment]
Bringing in typescript wouldn't mean that it's no longer js compatible, but it would add a somewhat large dependency.  But, since alias hq itself is a dev dependency, maybe it's not really a big deal.

**Comment by davestewart** [comment]
Re the trailing comma, this rx seems to handle it:

```js
json = json.replace(/,+(\s+[}\]])/g, '$1')
```

Comments on their own line could be handled like so:

```js
json = json.replace(/(^\s+\/\/.+$|\/\/[^"]+$)/gm, '')
```

This is just some mucking about in a scratchpad, but might be a quick win for this issue.

#30 would be a bit more work.

**Comment by IanVS** [comment]
Maybe take a look at https://github.com/davestewart/alias-hq/pull/37 and see if that might be a good solution?

**Comment by davestewart** [comment]
I just noticed you have 🦆, + 🐝  in your profile. Two of my 3 favourite creatures along with 🐙  !
