### ISSUE TITLE
Add types

### ISSUE THREAD

**Issue by anbraten** [davestewart/alias-hq#29]
I tried to use your package inside a `jest.config.ts`, but it does not seem to have types for itself? Would be quite nice if that would be possible.

**Comment by davestewart** [comment]
Oooh blimey, TS Jest is not something I had considered!

Can you `tsignore` it for now?

**Comment by davestewart** [comment]
Fixed in 044bae3981f90906e558a9aaafdfa648c35002c4.

@anbraten LMK if this works for you
