### ISSUE TITLE
Consider using older TS version

### ISSUE THREAD

**Issue by IanVS** [davestewart/alias-hq#41]
After adding typescript as a dependency in https://github.com/davestewart/alias-hq/pull/37, I found that updating alias-hq also updated the version of typescript being used in my project, which caused some failures since I went from 4.4 to 4.5, and typescript treats minor version updates as breaking.  I can solve this by using `4.4.x` in my package.json, but this could cause confusion for others as well, so what do you think about using an older version of typescript that still supports the methods needed, so that an accidental upgrade is less likely?

**Comment by davestewart** [comment]
TBH I was never really comfortable with the TS dependency, as Alias is supposed to be pretty much agnostic, aside from the configuration format.

My gut feeling is to ditch TS and use JSON5 and write the (I presume trivial) code needed to resolve the paths.

**Comment by IanVS** [comment]
I don't have the time to help out with that right now, but seems like a decent approach to me.

**Comment by davestewart** [comment]
Yeah, no problem.

My guess is that it's unlikely to trip too many people up for right this second, so maybe I can take a look at it in the coming week(s).

**Comment by IanVS** [comment]
It might be worth considering using https://github.com/privatenumber/get-tsconfig, which doesn't have a dependency on TS.

**Comment by IanVS** [comment]
@davestewart what do you think about ^?  Worth an experiment to see how it works?

**Comment by davestewart** [comment]
Yeah, I think it's a good idea.

I need to be able to write back to the file as well in the CLI.

There do seem to be some NPM packages to do this, but maybe I can treat them as separate problems for the time being
