### ISSUE TITLE
Incorrect type for `load` function

### ISSUE THREAD

**Issue by BenShelton** [davestewart/alias-hq#42]
The generated type for the `load` function is marked as `value?: undefined` but it should actually be `value? string`.

The generated type looks like this:
```ts
/**
 * Load config
 *
 * @param   {undefined}         value     Pass no value for to determine config file automatically
 * @param   {string}            value     Pass an absolute path to load from alternate location
 * @returns {object}                      The Alias HQ instance
 */
export function load(value?: undefined): object;
```

I believe the JSDoc here is incorrect, the `value` param should be combined into one and written as `[value]` instead to mark as optional, according to the docs: https://jsdoc.app/tags-type.html

The code line in question is here:

https://github.com/davestewart/alias-hq/blob/19309203d65893dab77c2d71e1fa26a16e8034ad/src/index.js#L190

**Comment by davestewart** [comment]
Ah, good spot!

Thanks, I'll take a look.

Planning to fit in lots of lovely OSS work over Christmas so hopefully not too long

**Comment by davestewart** [comment]
Fixed and published on NPM as 5.3.2 👍

**Comment by davestewart** [comment]
Crap. Just realised I left the other line in. LMK if this is an issue right now, otherwise I'll fix in a future update.

**Comment by BenShelton** [comment]
Seems to work fine for now.

<img width="441" alt="Screenshot 2022-01-12 at 10 16 20" src="https://user-images.githubusercontent.com/22983604/149121490-26a090d6-c6b5-4341-b3e3-38a94b8ed0eb.png">

Thanks for fixing this.

**Comment by davestewart** [comment]
Oh, nice, I like how the popup shows the actual docs text.

Is that VS Code?

**Comment by BenShelton** [comment]
> Oh, nice, I like how the popup shows the actual docs text.
> 
> Is that VS Code?

Yes that's the VSCode intellisense, just by hovering over it. Should work in `.js` files too.
