### ISSUE TITLE
How to register aliases with ts-node

### ISSUE THREAD

**Issue by andidev** [davestewart/alias-hq#46]
How to register aliases with ts-node like when using tsconfig-paths? 

```
ts-node -r tsconfig-paths/register main.ts
```

**Comment by davestewart** [comment]
Not sure about the question or potential answers.

Can you provide some additional context / info?

**Comment by andidev** [comment]
We have TypeScript scripts configured in package.json that uses alias paths. Currently we use `tsconfig-paths` to add support for alias imports. Would be great to be able to use alias-hq here as well instead of using two libs.

Currently we run scripts with the following command:
```bash
./node_modules/.bin/ts-node -x .ts -r tsconfig-paths/register --no-warnings scripts/package/release.ts
```

**Comment by diegoulloao** [comment]
I think currently is not possible to require alias-hq like yo do with tsconfig-paths.
I was trying to do the same, would be wonderful to have this option available soon, I think it's a must have actually.

Only option for now is to add a require statement at the beginning of your index/main.js file

```js
require("alias-hq").get("module-alias")

// ... rest of app
```

**Comment by diegoulloao** [comment]
I was thinking how to do it by hand... I'm improvising this code:

`src/scripts/alias-hq`
```ts
require("alias-hq").get("module-alias")
```
Then add the script to your `package.json`
```json
{
  "scripts": {
    "dev": "ts-node -r src/scripts/alias-hq src/index.ts"
  },
}
```

**Comment by diegoulloao** [comment]
I opened this PR! #48

**Comment by davestewart** [comment]
Hey all.

Sorry for the delay. Have had time to look at this now.

@diegoulloao - thanks for your demo and also your PR, that does make things clearer.

However, from what I can tell, this is just implementing Alias HQ in a script, in the same way one would do for any other framework (Jest, Webpack, etc).

Is that right?

**Comment by davestewart** [comment]
Closed by #48

**Comment by andidev** [comment]
@davestewart looks like current solution is causing issues when running scripts not in root project folder. package.json does not seem to be found.
This makes running scripts from WebStorm fail so we cannot still replace tsconfig-paths with alias-hq fully 😞 
Screenshot of this issue reproduced with alias-hq from terminal and how same works with tsconfig-paths.
![image](https://user-images.githubusercontent.com/571389/165052023-cc462213-9b21-4c85-b261-12bd75f7eb1d.png)

I am guessing this is caused by how alias-hq looks for package.json is different from tsconfig-paths. Or maybe tsconfig-paths dont load the package.json at all since it has no settings saved there not sure.
Is it possible to change that in case package.json is not found it does not throw an error? Or maybe it looks for a package.json file further up in the directory tree until it finds one?
I can provide a PR for this if its ok.

**Comment by davestewart** [comment]
OK, thanks for the heads up!

I'll have a fiddle...

**Comment by davestewart** [comment]
Just looking at this now. 

So I think Alias expects the script to be run from the same folder the `package.json` is in.

@andidev - you say you're running the script from another folder. Can you give some more context as to where everything is and where you are running from?
