### ISSUE TITLE
Change JSON parser to JSON5

### ISSUE THREAD

**Issue by Nike682631** [davestewart/alias-hq#63]
Currently aliasHQ seems to be using a parser that does not recognizes comments in JSON. This can be problematic as many projects that might be allowing comments in their tsconfigs suddenly won't be able to do so if they use aliasHQ for parsing. This issue is to address that problem.

**Comment by IlCallo** [comment]
For reference, a quick fix would be to change this line

https://github.com/davestewart/alias-hq/blob/cde1ee04ed1e36a90b6909a6b8da5805923a990b/cli/utils/file.js#L12

to use [`JSON5.parse(text)`](https://github.com/json5/json5#json5parse)

**Comment by davestewart** [comment]
Hey folks, yes, completely agree and this is on the list!

- https://github.com/davestewart/alias-hq/issues/41
- https://github.com/davestewart/alias-hq/issues/40

For context, Alias HQ also needs to write to JSON, though this shouldn't prevent this from happening.

This is something I have wanted to fix for ages, so let me try and find some time over the weekend.

**Comment by IlCallo** [comment]
Reading JSONC is pretty straightforward, while writing to JSONC format is tricky, so tricky that JSON5 mantainer just decided to not support it 
Can we contribute with the small fix using JSON5 only for reading in the meantime?

After all, it seems that you would need to write to JSON only when initializing the project with isn't using new aliases, not when the user already setup its own aliases

**Comment by davestewart** [comment]
Yes please, go for it!

**Comment by Nike682631** [comment]
@davestewart  I'm pretty sure we were using the latest package version. I'll have to check this out again but I think adding aliashq was when the comments started to break the project.

**Comment by davestewart** [comment]
If you have time to check, that would be great. I'll continue work on this anyway

**Comment by davestewart** [comment]
Hey @Nike682631,

I just checked your PR:

https://github.com/quasarframework/quasar/pull/15702/files#diff-be6b822ab67a48c0e358715e97aa5d060dd9aa2cea5e44ab9ae59a9e28f680ddR58

Looks like that is v2.x and Alias is now on 6.1.0 and supported comments since [5.3](https://github.com/davestewart/alias-hq/blob/main/CHANGELOG.md#530---2021-11-25).

So, update to the latest and you should be good to go!

I'll leave this open until you've had time to check.

**Comment by davestewart** [comment]
No problem. Thanks for using Alias HQ!
