### ISSUE TITLE
Tsconfig parser does not support Node.js-style resolution of the `extends` field

### ISSUE THREAD

**Issue by bjoluc** [davestewart/alias-hq#72]
#65 removed support for Node.js-style resolution of the tsconfig `extends` field – something that [TypeScript can do](https://www.typescriptlang.org/tsconfig#extends). Implementing this from-scratch is not entirely trivial, but [get-tsconfig](https://github.com/privatenumber/get-tsconfig) has it all. @davestewart Since you decided against `get-tsconfig`, I'm not sure if there's a reason not to use it in this project? If not, I'm happy to submit a PR (I'm desperately depending on module resolution in `extends` :smiling_face_with_tear:). Just drop me a thumbs-up reaction here if `get-tsconfig` would also work.

**Comment by davestewart** [comment]
Ah! Wasn't aware there was a difference. That was removed for other reasons. If this other package does it right then it's a candidate.

Let me take a look later today (actually have some free time as I'm on holiday) and report back 👍

**Comment by bjoluc** [comment]
Thanks for the super-fast reply! For the reference and maybe to save you some time, [here](https://github.com/microsoft/TypeScript/blob/6d520282878f87d381d5ce8cf465f1e16a54e797/src/compiler/commandLineParser.ts#L3297)'s how TS resolves `extends` paths and [here](https://github.com/privatenumber/get-tsconfig/blob/c834d2322f560754b2a857fe2a94ad619908991c/src/parse-tsconfig/resolve-extends-path.ts#L66)'s how get-tsconfig does it.

**Comment by davestewart** [comment]
The README for the project looks just the ticket.
