### ISSUE TITLE
npm dependencies

### ISSUE THREAD

**Issue by tinohager** [davestewart/alias-hq#77]
Thank you for your work on your package. I am working with the Quasar framework and we found out that some dependencies should be updated. Could you possibly publish an updated version. Many thanks in advance

- jscodeshift@0.13.1 -> 0.16.1
- inquirer@7.3.3 -> 10.1.6

The full report
https://npmgraph.js.org/?q=alias-hq@6.2.3#color=outdated&zoom=w

**Comment by davestewart** [comment]
Thanks for the info! I'll take a look at the weekend

**Comment by tinohager** [comment]
Thank you very much for the quick feedback

**Comment by jodeleeuw** [comment]
We're in a similar situation - would be very grateful for an update!

**Comment by davestewart** [comment]
Thanks for the nudge, Josh!

**Comment by tinohager** [comment]
Hi, have you by any chance had time to devote to the subject yet?

**Comment by tinohager** [comment]
Hi, have you by any chance had time to devote to the subject yet?

**Comment by davestewart** [comment]
Hey, thanks for the second nudge.

Actually spent all weekend on open source, so rest assured I've found time to look at all my projects again! 

This should be an easy one, so I'll take a look first thing Monday morning. 

Thanks for your patience!

**Comment by davestewart** [comment]
OK, all done and published!

Sorry for the delay and impact on related projects.

Looks like I need to take a look at the whole project again soon, maybe upgrade to ES modules too.

**Comment by tinohager** [comment]
@davestewart Thanks, for the update.
It would probably be great if we could also bring [jscodeshift](https://github.com/facebook/jscodeshift) to version 17.

**Comment by davestewart** [comment]
> We needed to go [from v0.x to a major release](https://github.com/facebook/jscodeshift/issues/593), and it may as well happen now

Ha ha ha; no problem!

I'll see what I can do soon

**Comment by tinohager** [comment]
`vue-jscodeshift-adapter` is also on version `2.2.1` the current version is `3.0.0`

**Comment by tinohager** [comment]
A good overview is available here https://npmgraph.js.org/?q=alias-hq#color=outdated&select=exact%3Anode-fetch%402.7.0

**Comment by tinohager** [comment]
node-fetch should be replace with axios? (the latest version 3.3.2 also has outdated packages and the maintenance does not look good)
https://github.com/davestewart/alias-hq/blob/main/cli/services/docs.js

**Comment by davestewart** [comment]
> A good overview is available here [npmgraph.js.org?q=alias-hq#color=outdated&select=exact%3Anode-fetch%402.7.0](https://npmgraph.js.org/?q=alias-hq#color=outdated&select=exact%3Anode-fetch%402.7.0)

That's pretty neat!

> node-fetch should be replace with axios? (the latest version 3.3.2 also has outdated packages and the maintenance does not look good)

It's really only used for fetching the list of integrations, so not sure I want to add 2MB on just for that.

Is it an issue for your current use case?

**Comment by tinohager** [comment]
No it is not, I have also seen that as of nodejs v18 fetch is a fixed part of nodejs.
https://nodejs.org/dist/latest-v18.x/docs/api/globals.html#fetch

**Comment by tinohager** [comment]
@davestewart  little nudge 😃

**Comment by tinohager** [comment]
@davestewart little nudge 😃

**Comment by tinohager** [comment]
I wanted to politely ask if you still have any plans to release an update in the future? I really appreciate all the work you've done on this project and would be grateful for any information.

**Comment by davestewart** [comment]
Hey!

Sorry for missing your comments for all this time.

I've set aside time this week to work on OSS so will be looking at this again 🙏

**Comment by tinohager** [comment]
Great news 🚀
